baseURL = 'https://aquanjsw.github.io/'
languageCode = 'zh-cn'
title = "aquanjsw's blog"
theme = 'paper'
hasCJKLanguage = true

[services]
  [services.googleAnalytics]
    ID = 'G-68SK6F8G3S'
    
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true